# Generated by Django 4.1.7 on 2023-02-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceId',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('regno', models.CharField(max_length=50)),
            ],
        ),
    ]
