# Generated by Django 4.1.7 on 2023-03-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceId',
            fields=[
                ('id', models.IntegerField(auto_created=True)),
                ('regno', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
