# Generated by Django 4.1.7 on 2023-04-18 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listMed_app', '0010_medmodel_doc_id_medmodel_doc_name'),
        ('patientsapp', '0003_alter_patientsmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='medAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('morningTaken', models.CharField(blank=True, max_length=25, null=True)),
                ('noonTaken', models.CharField(blank=True, max_length=25, null=True)),
                ('eveningTaken', models.CharField(blank=True, max_length=25, null=True)),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medAnalytics', to='listMed_app.medmodel')),
                ('medName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedModel', to='listMed_app.medmodel')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medAnalytics', to='patientsapp.patientsmodel')),
            ],
        ),
    ]
