# Generated by Django 4.1.7 on 2023-03-08 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedModel',
            fields=[
                ('id', models.IntegerField(auto_created=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('medName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('beforeFood', models.BooleanField(default=False)),
                ('medMorning', models.BooleanField(default=False)),
                ('medNoon', models.BooleanField(default=False)),
                ('medEvening', models.BooleanField(default=False)),
            ],
        ),
    ]
