# Generated by Django 4.1.7 on 2023-03-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listMed_app', '0003_alter_medmodel_id_alter_medmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
