# Generated by Django 4.1.7 on 2023-03-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listMed_app', '0004_alter_medmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medmodel',
            name='afterFood',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medmodel',
            name='beforeFood',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='medmodel',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medmodel',
            name='medEvening',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='medmodel',
            name='medMorning',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='medmodel',
            name='medNoon',
            field=models.BooleanField(),
        ),
    ]
