# Generated by Django 4.1.7 on 2023-03-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listMed_app', '0005_medmodel_afterfood_alter_medmodel_beforefood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medmodel',
            name='afterFood',
            field=models.BooleanField(default=True),
        ),
    ]
