# Generated by Django 4.1.7 on 2023-04-06 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0003_alter_patientsmodel_id'),
        ('listMed_app', '0008_rename_afterfood_medmodel_medicinetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='medmodel',
            name='p_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MedModel', to='patientsapp.patientsmodel'),
            preserve_default=False,
        ),
    ]
