# Generated by Django 4.1.7 on 2023-04-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listMed_app', '0009_remove_medmodel_user_id_medmodel_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medmodel',
            name='doc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medmodel',
            name='doc_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
