# Generated by Django 4.1.7 on 2023-02-25 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drmodel',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
