# Generated by Django 4.1.7 on 2023-03-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0003_alter_drmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drmodel',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
