# Generated by Django 4.1.7 on 2023-04-04 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='patientsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=25)),
                ('p_email', models.EmailField(max_length=25, unique=True)),
                ('p_bloodGroup', models.CharField(max_length=10)),
                ('p_dob', models.DateField()),
                ('nfc_id', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientModel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
