# Generated by Django 4.1.7 on 2023-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsmodel',
            name='nfc_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
