# Generated by Django 4.1.7 on 2023-04-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0002_alter_patientsmodel_nfc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
